# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类名')),
                ('ClassIntro', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类简介')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpuName', models.CharField(blank=True, max_length=50, null=True, verbose_name='spu名称')),
                ('SpuIntro', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类简介')),
            ],
        ),
    ]
