# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='unit',
            field=models.SmallIntegerField(choices=[(1, '箱'), (2, '斤'), (3, '个'), (4, '台')], default=3, verbose_name='单位'),
        ),
    ]
