# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='活动名')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('a_url', models.URLField(verbose_name='url地址')),
            ],
            options={
                'verbose_name': '首页活动表',
                'verbose_name_plural': '首页活动表',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
                'db_table': 'cycle',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品相册',
                'verbose_name_plural': '商品相册',
                'db_table': 'goods_img',
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品名')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='价格')),
                ('unit', models.SmallIntegerField(choices=[(1, '箱'), (2, '斤'), (3, '个')], default=3, verbose_name='单位')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('sales', models.IntegerField(verbose_name='销量')),
                ('url', models.URLField(verbose_name='logo地址')),
                ('is_sale', models.BooleanField(default=True, verbose_name='是否上架')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品库存',
                'verbose_name_plural': '商品库存',
                'db_table': 'goods_sku',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='活动专区名称')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_on', models.BooleanField(default=True, verbose_name='是否上架')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '活动专区',
                'verbose_name_plural': '活动专区',
                'db_table': 'special',
            },
        ),
        migrations.CreateModel(
            name='SpecialGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_goods.GoodsSku', verbose_name='商品sku id')),
                ('special_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_goods.Special', verbose_name='活动专区id')),
            ],
            options={
                'verbose_name': '活动专区商品表',
                'verbose_name_plural': '活动专区商品表',
                'db_table': 'special_goods',
            },
        ),
        migrations.AlterModelOptions(
            name='goodsclass',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelOptions(
            name='goodsspu',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelTable(
            name='goodsclass',
            table='goods_class',
        ),
        migrations.AlterModelTable(
            name='goodsspu',
            table='goods_spu',
        ),
        migrations.AddField(
            model_name='goodssku',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_goods.GoodsClass', verbose_name='商品分类id'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_goods.GoodsSpu', verbose_name='商品spu'),
        ),
        migrations.AddField(
            model_name='goodsimg',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_goods.GoodsSku', verbose_name='商品sku id'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_goods.GoodsSku', verbose_name='商品sku id'),
        ),
    ]
