# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0002_auto_20181123_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsclass',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品sku', 'verbose_name_plural': '商品sku'},
        ),
        migrations.AlterModelOptions(
            name='goodsspu',
            options={'verbose_name': '商品spu', 'verbose_name_plural': '商品spu'},
        ),
    ]
