# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0002_auto_20181123_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
